import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from 'next/font/google'
import { getServerSession } from "next-auth";
import { authOption } from "./api/auth/[...nextauth]/options";
import SessionSetter from "@/components/utility/SessionSetter";

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: "Triangulum",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOption);
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.className}`}>
        {children}
        <SessionSetter session={session} />
      </body>
    </html>
  );
}
