run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - gosimple
    - staticcheck
    - structcheck
    - unused
    - deadcode
    - gofmt
    - goimports

issues:
  exclude-use-default: false
