import { QuestionType } from '@/types/prisma-types';
import { v4 as uuid } from 'uuid';

export function generateDefaultQuestions(): QuestionType[] {
    const questions: Omit<QuestionType, 'id' | 'quizId' | 'imageUrl'>[] = [
        {
            question: 'Which technology powers Web3 applications?',
            options: ['Cloud Servers', 'Blockchain', 'Virtual Machines', 'Traditional Databases'],
            correctAnswer: 1,
            explanation: 'Web3 applications run on decentralized blockchain networks.',
            hint: 'It’s the same tech behind Bitcoin and Ethereum.',
            difficulty: 1,
            basePoints: 100,
            timeLimit: 25,
            readingTime: 3,
            orderIndex: 1,
            isAsked: false,
        },
        {
            question: 'What is the main difference between Web2 and Web3?',
            options: [
                'Web2 is decentralized, Web3 is centralized',
                'Web2 focuses on read-write, Web3 focuses on read-write-own',
                'Web2 uses blockchain, Web3 uses databases',
                'Web2 has smart contracts, Web3 does not',
            ],
            correctAnswer: 1,
            explanation:
                'Web2 is about read and write, while Web3 adds ownership through decentralization and blockchain.',
            hint: 'Think about ownership of content and data.',
            difficulty: 2,
            basePoints: 150,
            timeLimit: 35,
            readingTime: 5,
            orderIndex: 0,
            isAsked: false,
        },
        {
            question: 'In Web2, data is primarily controlled by:',
            options: [
                'Individual Users',
                'Decentralized Nodes',
                'Centralized Companies',
                'Smart Contracts',
            ],
            correctAnswer: 2,
            explanation:
                'In Web2, big tech companies like Google, Meta, and Amazon control most user data.',
            hint: 'Think Facebook, Google, and Amazon.',
            difficulty: 1,
            basePoints: 100,
            timeLimit: 20,
            readingTime: 3,
            orderIndex: 2,
            isAsked: false,
        },
        {
            question: 'Which of the following is a Web3 wallet?',
            options: ['Google Drive', 'MetaMask', 'Dropbox', 'Facebook'],
            correctAnswer: 1,
            explanation: 'MetaMask is a crypto wallet used to interact with Web3 applications.',
            hint: 'It’s one of the most popular Ethereum wallets.',
            difficulty: 1,
            basePoints: 100,
            timeLimit: 20,
            readingTime: 3,
            orderIndex: 3,
            isAsked: false,
        },
        {
            question: 'What is a smart contract in Web3?',
            options: [
                'A contract signed digitally via email',
                'A program that automatically executes agreements on the blockchain',
                'A faster version of a PDF contract',
                'A legal document stored in the cloud',
            ],
            correctAnswer: 1,
            explanation:
                'Smart contracts are self-executing programs on the blockchain that enforce agreements without intermediaries.',
            hint: 'Think of a vending machine on blockchain.',
            difficulty: 2,
            basePoints: 150,
            timeLimit: 40,
            readingTime: 4,
            orderIndex: 4,
            isAsked: false,
        },
        {
            question: 'Which is an example of a Web2 application?',
            options: ['Instagram', 'Uniswap', 'OpenSea', 'Ethereum'],
            correctAnswer: 0,
            explanation:
                'Instagram is a Web2 platform owned by Meta and relies on centralized servers.',
            hint: 'It’s owned by Meta.',
            difficulty: 1,
            basePoints: 100,
            timeLimit: 25,
            readingTime: 3,
            orderIndex: 5,
            isAsked: false,
        },
        {
            question: 'Which is an example of a Web3 application?',
            options: ['Twitter', 'Amazon', 'Uniswap', 'YouTube'],
            correctAnswer: 2,
            explanation:
                'Uniswap is a decentralized finance (DeFi) application built on blockchain, representing Web3.',
            hint: 'It’s a decentralized exchange (DEX).',
            difficulty: 2,
            basePoints: 150,
            timeLimit: 30,
            readingTime: 4,
            orderIndex: 6,
            isAsked: false,
        },
        {
            question: 'How are identities managed in Web3 compared to Web2?',
            options: [
                'Web2 uses usernames/passwords, Web3 uses cryptographic wallets',
                'Both use the same login methods',
                'Web2 uses biometrics, Web3 uses phone numbers',
                'Web3 does not require identity verification',
            ],
            correctAnswer: 0,
            explanation:
                'Web2 relies on accounts and passwords, while Web3 identities are tied to cryptographic wallets.',
            hint: 'Think private keys vs. passwords.',
            difficulty: 2,
            basePoints: 150,
            timeLimit: 35,
            readingTime: 5,
            orderIndex: 7,
            isAsked: false,
        },
        {
            question: 'What is the economic model of Web3?',
            options: [
                'Ad-based revenue controlled by platforms',
                'Ownership and tokens for users',
                'Subscription-only services',
                'Free access without monetization',
            ],
            correctAnswer: 1,
            explanation:
                'Web3 promotes user ownership through tokens, NFTs, and decentralized governance.',
            hint: 'Think tokens and NFTs.',
            difficulty: 2,
            basePoints: 150,
            timeLimit: 30,
            readingTime: 4,
            orderIndex: 8,
            isAsked: false,
        },
        {
            question: 'Which statement about Web2 vs Web3 is correct?',
            options: [
                'Web2 prioritizes decentralization, Web3 prioritizes centralization',
                'Web2 is blockchain-based, Web3 is cloud-based',
                'Web2 data is owned by corporations, Web3 data is owned by users',
                'Web3 has no relation to blockchain',
            ],
            correctAnswer: 2,
            explanation:
                'In Web2, companies own and control data, while Web3 aims to give users ownership of their data via blockchain.',
            hint: 'Who owns the data?',
            difficulty: 2,
            basePoints: 150,
            timeLimit: 40,
            readingTime: 5,
            orderIndex: 9,
            isAsked: false,
        },
    ];

    return questions.map((q, index) => ({
        ...q,
        id: uuid(),
        quizId: '',
        imageUrl: '',
        orderIndex: index,
    }));
}
