import { QuestionType } from '@/types/prisma-types';
import { v4 as uuid } from 'uuid';

export function generateDefaultQuestions(): QuestionType[] {
    const questions: Omit<QuestionType, 'id' | 'quizId' | 'imageUrl'>[] = [
        {
            question: 'What is the capital city of Japan?',
            options: ['Kyoto', 'Osaka', 'Tokyo', 'Hiroshima'],
            correctAnswer: 2,
            explanation: 'Tokyo is the capital city of Japan.',
            difficulty: 1,
            basePoints: 100,
            timeLimit: 25,
            readingTime: 3,
            orderIndex: 0,
            isAsked: false,
        },
        {
            question: 'Which gas do plants absorb from the atmosphere?',
            options: ['Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Hydrogen'],
            correctAnswer: 1,
            explanation: 'Plants absorb carbon dioxide for photosynthesis.',
            difficulty: 1,
            basePoints: 100,
            timeLimit: 25,
            readingTime: 3,
            orderIndex: 1,
            isAsked: false,
        },
        {
            question: 'Which programming language is known for its snake logo?',
            options: ['Python', 'Java', 'Ruby', 'C#'],
            correctAnswer: 0,
            explanation: 'Python is represented by a snake logo.',
            difficulty: 1,
            basePoints: 100,
            timeLimit: 30,
            readingTime: 4,
            orderIndex: 2,
            isAsked: false,
        },
        {
            question: 'Who wrote the novel "1984"?',
            options: ['Aldous Huxley', 'George Orwell', 'J.K. Rowling', 'Mark Twain'],
            correctAnswer: 1,
            explanation: '"1984" was written by George Orwell.',
            difficulty: 2,
            basePoints: 150,
            timeLimit: 35,
            readingTime: 5,
            orderIndex: 3,
            isAsked: false,
        },
        {
            question: 'Which element is needed for strong bones and teeth?',
            options: ['Iron', 'Calcium', 'Potassium', 'Zinc'],
            correctAnswer: 1,
            explanation: 'Calcium is essential for strong bones and teeth.',
            difficulty: 1,
            basePoints: 100,
            timeLimit: 20,
            readingTime: 3,
            orderIndex: 4,
            isAsked: false,
        },
        {
            question: 'What is the main purpose of a blockchain?',
            options: [
                'Store large files',
                'Track transactions securely',
                'Run websites',
                'Send emails faster',
            ],
            correctAnswer: 1,
            explanation: 'Blockchains securely track transactions across a network.',
            difficulty: 2,
            basePoints: 150,
            timeLimit: 40,
            readingTime: 4,
            orderIndex: 5,
            isAsked: false,
        },
        {
            question: 'Which planet is known as the Red Planet?',
            options: ['Mars', 'Venus', 'Jupiter', 'Saturn'],
            correctAnswer: 0,
            explanation: 'Mars is often called the Red Planet because of its reddish appearance.',
            difficulty: 1,
            basePoints: 100,
            timeLimit: 25,
            readingTime: 3,
            orderIndex: 6,
            isAsked: false,
        },
        {
            question: 'What does HTTP stand for?',
            options: [
                'HyperText Transfer Protocol',
                'Hyperlink Text Transmission Program',
                'High Transfer Text Protocol',
                'Hyper Transfer Transfer Process',
            ],
            correctAnswer: 0,
            explanation: 'HTTP stands for HyperText Transfer Protocol.',
            difficulty: 2,
            basePoints: 150,
            timeLimit: 30,
            readingTime: 4,
            orderIndex: 7,
            isAsked: false,
        },
        {
            question: 'Which organ in the human body produces insulin?',
            options: ['Liver', 'Pancreas', 'Kidney', 'Heart'],
            correctAnswer: 1,
            explanation: 'The pancreas produces insulin to regulate blood sugar levels.',
            difficulty: 2,
            basePoints: 150,
            timeLimit: 30,
            readingTime: 4,
            orderIndex: 8,
            isAsked: false,
        },
        {
            question: 'Which of the following is a renewable energy source?',
            options: ['Coal', 'Oil', 'Solar', 'Natural Gas'],
            correctAnswer: 2,
            explanation: 'Solar energy is a renewable source of energy.',
            difficulty: 1,
            basePoints: 100,
            timeLimit: 20,
            readingTime: 3,
            orderIndex: 9,
            isAsked: false,
        },
    ];

    return questions.map((q, index) => ({
        ...q,
        id: uuid(),
        quizId: '',
        imageUrl: '',
        orderIndex: index,
    }));
}
