name: CI

on:
  pull_request:
    branches: [dev]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies (Yarn Workspaces)
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Check types
        run: yarn check-types

      - name: Format Check (Prettier)
        run: yarn format --check

      - name: Build
        run: yarn build
